/**:
  ros__parameters:
    clip_ball_xy: True
    filter_ball_xy: True
    set_fixed_z: True

    enable_delay: False
    delay_time: 0.25

    # xmin, ymin, xmax, ymax
    xy_clip_limits: [-2.000, -1.000, 2.000, 1.711]
    xy_filter_limits: [-3.000, -2.000, 3.000, 2.711]