/**:
  ros__parameters:
    base2cam_translation: [0.120, 0.040, 0.510] 
    base2cam_ypr: [-90.0, 0.0, -102]

    extrapolate: False
    set_true_z: False

    clip_ball_xy: True
    x_min: -1.00
    x_max: 6.00
    y_min: -4.00
    y_max: 4.00