/**:
  ros__parameters:
    base2cam_translation: [-0.020, 0.045, 0.645] 
    base2cam_ypr: [-90.0, 0.0, -103.0]

    extrapolate: False
    set_true_z: False

    clip_ball_xy: True
    x_min: 0.45
    x_max: 8.00
    y_min: -0.28
    y_max: 8.00