/**:
  ros__parameters:
    timer_period_sec: 0.03     # in seconds

    clamp_goalpose: True
    yaw_for_corners: False
    yaw_90: True

    lock_far_target: True
    far_threshold: 1.00  # In meters

    # Offset from base_link to intake
    x_intake_offset: 0.35
    y_intake_offset: 0.00

    ## XY clamp limits for goalpose
    # xmin, ymin, xmax, ymax
    goalpose_limits:  [-1.75, -3.50, 1.75, 1.35]

    ## XY limits for collision free-movement
    # xmin, ymin, xmax, ymax
    safe_xy_limits: [-1.30, -3.00, 1.30, 1.10]

    ## Only give absolute yaw for corners if yaw_for_corners is True
    # And if base2target distance is less than this value
    offset_distance: 1.0

    ## Give a farther goalpose so that ball gets inside intake even if it is not detected
    enable_dash_at_end: True
    dash_zone: 0.70
    dash_distance: 0.40

    ## Buffer distance for aligning intake (if always yaw = 90 degrees)
    enable_align_zone: True
    align_distance: 0.30
    x_align_tolerance: 0.10

    ## Dead zone i.e. target_ball is visible but robot cannot reach
    enable_deadZone: True
    deadZone_tolerance: 0.00
    increase_deadZone_x: 0.05
    backward_distance: 0.30

    ## Continuos goalpose
    enable_continuous_goalpose: False
    continuous_goalpose_duration: 0.100      # In seconds

    ## Dash forward if ball present in certain region of image
    enable_incremental_dash: False
    # XYXY ROI for ball detection
    incremental_dash_roi: [420, 410, 910, 550]
    roi_match_fraction: 0.33
    # Increments w.r.t. map
    x_increment_dash: 0.10
    y_increment_dash: 0.20

    enable_goalpose_lock: False
    goalpose_consistency_counter: 5
    goalpose_consistency_radius: 0.50
