/**:
  ros__parameters:
    timer_period_sec: 0.03     # in seconds

    clamp_goalpose: False
    yaw_for_corners: False
    consistent_target: False
    yaw_90: False

    # Offset from base_link to intake
    x_intake_offset: 0.60
    y_intake_offset: 0.10

    ## XY clamp limits for goalpose
    # xmin, ymin, xmax, ymax
    goalpose_limits:  [-1.35, -0.60, 1.35, 1.10]

    ## XY limits for collision free-movement
    # xmin, ymin, xmax, ymax
    safe_xy_limits: [-1.30, -0.30, 1.30, 1.10]