/**:
  ros__parameters:
    timer_period_sec: 0.03     # in seconds

    clamp_goalpose: True
    yaw_for_corners: False
    yaw_90: True
    lock_far_target: False

    # Offset from base_link to intake
    x_intake_offset: 0.40
    y_intake_offset: 0.00

    ## XY clamp limits for goalpose
    # xmin, ymin, xmax, ymax
    goalpose_limits:  [-1.60, -3.00, 1.60, 1.50]

    ## XY limits for collision free-movement
    # xmin, ymin, xmax, ymax
    safe_xy_limits: [-1.30, -3.00, 1.30, 1.10]

    ## Only give absolute yaw for corners if yaw_for_corners is True
    # And if base2target distance is less than this value
    offset_distance: 1.0

    ## Buffer distance for aligning intake (if always yaw = 90 degrees)
    enable_align_zone: True
    align_distance: 0.30
    x_align_tolerance: 0.05