/**:
  ros__parameters:
    timer_period_sec: 0.03     # in seconds

    limit_ball_range: True
    clamp_goalpose: True
    yaw_for_corners: True

    # Offset from base_link to intake
    x_intake_offset: 0.60
    y_intake_offset: 0.15

    ## XY clamp limits for goalpose
    # xmin, ymin, xmax, ymax
    goalpose_limits:  [-1.35, -0.60, 1.35, 1.10]

    ## XY clamp limits for ball range
    # xmin, ymin, xmax, ymax
    ball_xy_limits: [-3.00, -1.00, 3.00, 2.00]
    # ball_xy_limits: [-5.000, -5.000, 5.000, 5.000]

    ## XY limits for collision free-movement
    # xmin, ymin, xmax, ymax
    safe_xy_limits: [-1.30, -0.30, 1.30, 1.10]