/**:
  ros__parameters:
    ## Location calculation method
    # Options: "SinglePointDepth", "HostSpatials"
    coordinate_calc_method: "SinglePointDepth"

    ## HostSpatials choices
    # Options: "bbox_center", "bbox_roi"
    host_spatials_method: "bbox_center"

    # Averaging neighboring pixels' depth for depth of a point
    neighbourhood_pixels: 4

    clip_depth: True
    min_depth: 0.60
    max_depth: 8.00

    compare_past_depth: True
    delta_depth_min: 0.005
    delta_depth_max: 0.500